[project]
name = "metadata_remover"
version = "1.6"
description = "Tool for removing metadata from images and videos"
license = {file = "LICENSE.txt"}
readme = "README.md"

dependencies = [
    "libmat2"
]
